### ISSUE TITLE
No such File or Directory error

### ISSUE THREAD

**Issue by NayamAmarshe** [jspw/VS-Code-Config#1]
```
> Executing task:  g++ -g PalindromicArray\PalindromicArray.cpp -o PalindromicArray.out && clear && timeout 10 /usr/bin/time -v --output sys.txt ./PalindromicArray.out < input.txt > output.txt && rm *out <

g++.exe: error: PalindromicArrayPalindromicArray.cpp: No such file or directory
g++.exe: fatal error: no input files
compilation terminated.
The terminal process "C:\Program Files\Git\bin\bash.exe '-c', ' g++ -g PalindromicArray\PalindromicArray.cpp -o PalindromicArray.out && clear && timeout 10 /usr/bin/time -v --output sys.txt ./PalindromicArray.out < input.txt > output.txt && rm *out'" failed to launch (exit code: 1).

Terminal will be reused by tasks, press any key to close it.
```
Here's my folder structure
![image](https://user-images.githubusercontent.com/25067102/92510497-9411d900-f229-11ea-8c85-92259b3b4f52.png)

**Comment by jspw** [comment]
please renamte the input.f and output.f into input.txt and output.txt.
secondly move the input and output file out of the PilandromicArray folder....
You dont need to create input and output files for every cpp file....
Just create these files in the base folder. 
The ".vscode" folder and  input,output files in the same folders and you can keep cpp file in the base folder or can create as many as folders you want inside the base folder and keep cpp files...

**Comment by jspw** [comment]
![gg](https://user-images.githubusercontent.com/40170955/92849849-959bf680-f40d-11ea-9bb0-da64cd532b0f.jpg)

**Comment by jspw** [comment]
I have recently added some edits in the repository to handle the errors found in windows specially.

**Note :** Don't keep the cpp file in the base folder. I mean you have to create one or more folders in the base folder (Base folder means where you opened your vs code or you can say vs code wrokspace folder).and the input and output file should be in the base folder.
like this...
![folders](https://user-images.githubusercontent.com/40170955/92920914-e420b380-f454-11ea-8e0a-296e2c05bffe.png)
not this ...
![dont](https://user-images.githubusercontent.com/40170955/92920924-eb47c180-f454-11ea-8be1-4ce03e4ebcbf.png)

**Comment by jspw** [comment]
Let me know that solve your issue @NayamAmarshe and thanks for informing.

**Comment by NayamAmarshe** [comment]
> Let me know that solve your issue @NayamAmarshe and thanks for informing.

Thanks! Issue was fixed :D

**Comment by akib35** [comment]
It's not working for me.
![Screenshot 2020-12-30 202827](https://user-images.githubusercontent.com/65163997/103357697-04e14780-4ade-11eb-91c0-31c6ab5f05da.png)
my task.json is also that you recommended.
![Screenshot 2020-12-30 202907](https://user-images.githubusercontent.com/65163997/103357747-23474300-4ade-11eb-8b93-37e62ef709ee.png)

**Comment by Saadbasheer** [comment]
![image](https://user-images.githubusercontent.com/25801370/146048527-54ba2e98-2e65-40ec-b4de-a0697330fec3.png)

what shoud i do?
![image](https://user-images.githubusercontent.com/25801370/146048655-bd384290-2c17-44c8-a3c3-198799c5a4f3.png)
my folders

**Comment by jspw** [comment]
@Saadbasheer  are you using [latest one](https://github.com/jspw/VS-Code-Config/blob/master/Config-Files/C&C++/Windows/tasks.json) ? I have recently updated the tasks.json file and doc. I should also mention that now the default terminal should be `cmd`  (i have also changed it recently). So you can keep your input.txt file in the base folder as shown in your screenshot of the file structure.

**Comment by jspw** [comment]
I think changing default terminal as `cmd` will solve your problem.

**Comment by N-u-h-i-n** [comment]
Assalamu Alaikum vaiya i don't know why my input and output is not coming , please help :(
![Screenshot (1298)](https://user-images.githubusercontent.com/84878707/147184388-42012f1c-56cf-4401-9320-66d8c683bc9b.png)

**Comment by jspw** [comment]
@N-u-h-i-n  can you give me some more detail about the error or someting like a screenshot?

**Comment by jspw** [comment]
why all folders are in `.vscode` folder which is a dedicated folder for your vs code!  

Pull out your personal folder out of the `.vscode` folder. Make sure your `task.json` is inside the `.vscode` 

@N-u-h-i-n

**Comment by jspw** [comment]
![](https://github.com/jspw/VS-Code-Config/raw/master/images/final%20look%20%20vs%20code.png)

**Comment by Axay** [comment]
![image](https://user-images.githubusercontent.com/60010213/159172737-0e372dac-8a32-4fe4-9aed-eac427b138f9.png)

Not working for me if you can help that would be great

**Comment by NayamAmarshe** [comment]
> ![image](https://user-images.githubusercontent.com/60010213/159172737-0e372dac-8a32-4fe4-9aed-eac427b138f9.png)
> 
> Not working for me if you can help that would be great

If you are asking me for help, sorry I don't use Windows anymore 😅 It's just too much of a hassle to set up gcc/g++ commands on Windows, it's just too much work and it's easy to break. I have since then moved to ZorinOS (Linux) and setting up C++ was literally painless, everything was correctly pre-configured.

**Comment by Axay** [comment]
> 

ok still thank you for your time.

**Comment by jspw** [comment]
@Axay which task.json file you are using ?

**Comment by Axay** [comment]
https://github.com/jspw/VS-Code-Config/blob/master/Config-Files/C%26C%2B%2B/Windows/tasks.json this one

**Comment by gauravjalap** [comment]
> I think changing default terminal as `cmd` will solve your problem. [Follow this section to set cmd or command prompt as default terminal](https://github.com/jspw/VS-Code-Config/blob/master/windows.md#terminal-setup) . May be you need to restart your vs code after that.

Output is showing in Output.txt but every time I have to close the terminal window. Is there any method by which the terminal window doesn't appear and I don't have to close it every time.

**Comment by jspw** [comment]
Thanks @gauravjalap for mentioning it. I hope #12 will fix the issue. 
Also you can fix this manually by adding  the lines below in your `tasks.json` file.
```
"presentation": {
        "reveal": "never"
}
```

**Comment by gauravjalap** [comment]
Thanks a lot.

**Comment by singh3abhi** [comment]
Hello,
I did all the steps correctly (hopefully) but nothing is printing in the output.txt :/
can anyone please help
I used the latest [tasks.json](https://github.com/jspw/VS-Code-Config/blob/main/Config-Files/C&C++/Windows/tasks.json) , cmd as default terminal and pressed control + shift + b
![image](https://user-images.githubusercontent.com/99040717/236899000-a5d50423-e048-4e10-86cc-ab9a763ad7e1.png)
