### ISSUE TITLE
Task not working with file name LearnC++.cpp

### ISSUE THREAD

**Issue by singh3abhi** [jspw/VS-Code-Config#13]
Hello
I recently discovered that when i am trying to run task in learn.cpp it is working fine but when I run same task in learnC++.cpp it showing me an error
Does anyone has any idea how I can solve this problem ?
i am using the  latest tasks.json file and cmd as default shell
![WhatsApp Image 2023-05-10 at 7 03 23 PM](https://github.com/jspw/VS-Code-Config/assets/99040717/7817ecc5-5d91-4ed9-a36f-010b0874faa9)

**Comment by jspw** [comment]
Hey @singh3abhi , Thanks for your concern. I have came to know that this is a issue of **cmd**  `copy` command. I'm working on that.

**Comment by jspw** [comment]
Hope #14  this fix the problem and again thanks for rising the issue @singh3abhi .

**Comment by singh3abhi** [comment]
> Hope #14 this fix the problem and again thanks for rising the issue @singh3abhi.

Thank you very much for solving the issue in such a short span of time, I really appreciate the efforts keep up the excellent work man.
As the problem is solved I am closing the issue.
