### ISSUE TITLE
VSCode Default Terminal (Windows) as PowerShell

### ISSUE THREAD

**Issue by jakubbester** [jspw/VS-Code-Config#15]
I was following the tutorial for getting everything working on Windows. I was wondering if it would be possible to make it, so that we can use PowerShell instead of having to set the default terminal as CMD?

**Comment by jspw** [comment]
It was config for `powershell` before, then we faced some complicated issues in windows related to powershell commads ad moved to `cmd`. i would like to **r&d** on that if I get some free time. 
I will highly appreciate if you could work on that concern and give a _pr_ and everything goes fine I will be happy to merge your pr. Thanks @jakubbester

**Comment by jakubbester** [comment]
I will take a look at it when I get the chance!
