### ISSUE TITLE
Vs code Config not working

### ISSUE THREAD

**Issue by Vinit-Pathak** [jspw/VS-Code-Config#16]
Whatever setting you've mentioned over here I have done all exactly but it's not working
when I press ctrl + shift + B then in downward something like building is happening for 5 seconds then it also stops
Please tell me how I can resolve this issue...

https://github.com/jspw/VS-Code-Config/assets/110463455/4ecf8687-c22c-479d-babf-6e3c5446c601

**Comment by jspw** [comment]
looks like there is a error in the build console. can you check and share the logs with me?  @Vinit-Pathak

**Comment by Vinit-Pathak** [comment]
which logs???
where can i find this logs??

**Comment by Vinit-Pathak** [comment]
or we can do one thing we can connect with each other through Snapchat or Instagram where I can share my anydesk code with you so that you can do the respective setting in my vscode

**Comment by Vinit-Pathak** [comment]
https://github.com/jspw/VS-Code-Config/assets/110463455/4426b76b-88c6-4622-b7cb-951c9ae6bba4

**Comment by Vinit-Pathak** [comment]
{
    "version": "2.0.0",
    "tasks": [
        {
            "label": "Compile and run",
            "type": "shell",
            "command": "",
            "args": [
                "copy",
                "\"${file}\"",
                "${workspaceFolder}\\jspwTest.cpp",
                "&&",
                "g++",
                "jspwTest.cpp",
                "-o",
                "jspwTest",
                "&&",
                "jspwTest",
                "<",
                "input.txt",
                ">",
                "output.txt",
                "&&",
                "del",
                "jspwTest.exe",
                "&&",
                "del",
                "jspwTest.cpp"
            ],
            "presentation": {
                "reveal": "never"
            },
            "group": "build",
            "problemMatcher": {
                "owner": "cpp",
                "fileLocation": [
                    "relative",
                    "${workspaceRoot}"
                ],
                "pattern": {
                    "regexp": "^(.*):(\\d+):(\\d+):\\s+(warning|error):\\s+(.*)$",
                    "file": 1,
                    "line": 2,
                    "column": 3,
                    "severity": 4,
                    "message": 5
                }
            }
        },
        {
            "type": "cppbuild",
            "label": "C/C++: g++.exe build active file",
            "command": "C:\\msys64\\mingw64\\bin\\g++.exe",
            "args": [
                "-fdiagnostics-color=always",
                "-g",
                "${file}",
                "-o",
                "${fileDirname}\\${fileBasenameNoExtension}.exe"
            ],
            "options": {
                "cwd": "${fileDirname}"
            },
            "problemMatcher": [
                "$gcc"
            ],
            "group": {
                "kind": "build",
                "isDefault": true
            },
            "detail": "Task generated by Debugger."
        }
    ]
}

**Comment by Vinit-Pathak** [comment]
Broo please reply....

**Comment by jspw** [comment]
@Vinit-Pathak  sorry, can you know me in [Facebook](https://www.facebook.com/shfttt) or [Instagram](https://www.instagram.com/mh_shfttt) or [LinkedIn](https://www.linkedin.com/in/mhshifat) ? We can have a meet call then.

**Comment by jspw** [comment]
We have talked about the issue and make it work.
So the issue was not in the config file. Let me clear a thing for new users of VS-Code, You need to open vs code in a folder and apply the configuration for work fine. If you just open the file in a **vscode** and try to run with `Ctrl+Shft+B`, it will not work though You have config it properly. 
Thanks @Vinit-Pathak  hope this issue is resolved and I am colsing the issue.
