### ISSUE TITLE
output.txt window does not show output , tasks.json shows errors  

### ISSUE THREAD

**Issue by AA-YUSHI** [jspw/VS-Code-Config#23]
hey 
after adding code in the tasks.jason file and performing all the steps as it is the termial shiw the following errors 
and even when the errors are solved the output.txt file does not show the output with the input.txt file input 

Executing task:  copy "C:\Users\Ayushi Shrivastava\c++ strivers\.vscode\demo.cpp" 'C:\Users\Ayushi Shrivastava\c++ strivers\jspwTest.cpp' && g++ jspwTest.cpp -o jspwTest && jspwTest < input.txt > output.txt && del jspwTest.exe && del jspwTest.cpp 

The terminal process "C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe -Command  copy "C:\Users\Ayushi Shrivastava\c++ strivers\.vscode\demo.cpp" 'C:\Users\Ayushi Shrivastava\c++ strivers\jspwTest.cpp' && g++ jspwTest.cpp -o jspwTest && jspwTest < input.txt > output.txt && del jspwTest.exe && del jspwTest.cpp" terminated with exit code: 1. 
 *  Terminal will be reused by tasks, press any key to close it. 

 *  Executing task:  copy "C:\Users\Ayushi Shrivastava\c++ strivers\.vscode\demo.cpp" 'C:\Users\Ayushi Shrivastava\c++ strivers\jspwTest.cpp' && g++ jspwTest.cpp -o jspwTest && jspwTest < input.txt > output.txt && del jspwTest.exe && del jspwTest.cpp 
 
 The terminal process "C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe -Command  copy "C:\Users\Ayushi Shrivastava\c++ strivers\.vscode\demo.cpp" 'C:\Users\Ayushi Shrivastava\c++ strivers\jspwTest.cpp' && g++ jspwTest.cpp -o jspwTest && jspwTest < input.txt > output.txt && del jspwTest.exe && del jspwTest.cpp" terminated with exit code: 1. 
 *  Terminal will be reused by tasks, press any key to close it. 

 *  Executing task:  copy "C:\Users\Ayushi Shrivastava\c++ strivers\.vscode\input.txt" 'C:\Users\Ayushi Shrivastava\c++ strivers\jspwTest.cpp' && g++ jspwTest.cpp -o jspwTest && jspwTest < input.txt > output.txt && del jspwTest.exe && del jspwTest.cpp 
 The terminal process "C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe -Command  copy "C:\Users\Ayushi Shrivastava\c++ strivers\.vscode\input.txt" 'C:\Users\Ayushi Shrivastava\c++ strivers\jspwTest.cpp' && g++ jspwTest.cpp -o jspwTest && jspwTest < input.txt > output.txt && del jspwTest.exe && del jspwTest.cpp" terminated with exit code: 1. 
 *  Terminal will be reused by tasks, press any key to close it. 

 *  Executing task:  copy "C:\Users\Ayushi Shrivastava\c++ strivers\.vscode\demo.cpp" 'C:\Users\Ayushi Shrivastava\c++ strivers\jspwTest.cpp' && g++ jspwTest.cpp -o jspwTest && jspwTest < input.txt > output.txt && del jspwTest.exe && del jspwTest.cpp

**Comment by jspw** [comment]
from your logs, i assume you are using powershell as default terminal in vscode. Change the default terminal as cmd and try again.

Thanks for the patience @AA-YUSHI

**Comment by jspw** [comment]
@AA-YUSHI , As it has been 3 weeks and no response from you, also from your logs, it's udentified that its not a issue to the configuration, I am going to close this issue after 1 day.
