### ISSUE TITLE
Using time(failed to run command '/usr/bin/time': No such file or directory)

### ISSUE THREAD

**Issue by akib35** [jspw/VS-Code-Config#3]
Can you explain elaborately how to use time? 
![image](https://user-images.githubusercontent.com/65163997/103451901-cc1abb80-4cf3-11eb-9774-62a6d5e872ac.png)
my command in wsl :
![image](https://user-images.githubusercontent.com/65163997/103451917-fec4b400-4cf3-11eb-9034-266f182eaf8c.png)
I'm using x64 Windows 10 and ubuntu as wsl2.

**Comment by jspw** [comment]
Problem is `time` is a tool for linux and you cant install or use it in windows.

**Comment by akib35** [comment]
Oh! I found it, I should have opened that folder in wsl. However, why don't you mention that 
![image](https://user-images.githubusercontent.com/65163997/103472486-59274880-4db8-11eb-9f30-87c38f9658b7.png)
here?
Thanks.
