### ISSUE TITLE
Ctrl + Shift + B produces unexpected errors.

### ISSUE THREAD

**Issue by sandip2224** [jspw/VS-Code-Config#4]
***The terminal process "C:\Program Files\Git\bin\bash.exe '-c', ' cp C:\Users\SD\Desktop\CP\Programs\test.cpp C:\Users\SD\Desktop\CP && g++ test.cpp -o test.out && ./test.out < input.txt > output.txt && rm *out && rm test.cpp'" failed to launch (exit code: 1).***

***Terminal will be reused by tasks, press any key to close it.***

P.S. I use Windows OS(64-bit)

![1](https://user-images.githubusercontent.com/61842142/105372344-820a6300-5c2b-11eb-8028-0faa982e746f.PNG)

**Comment by jspw** [comment]
Tell me somehting : 

-  Open terminal in the vs code

-   Go to the cpp file directory

 >       cd Programs


-  Use manual command 

    -  Build

    >      g++ test.cpp -o test.out 

    -   Run
   
    >      ./test.out

is this working fine in your machine ?
Is there any anivirus running ? like avast or something which can prevent running programmes ?
You can also delete the test.cpp file and create a new one and try again !

**Comment by sandip2224** [comment]
Yeah I tried the manual build commands but it asks for user input via the terminal itself instead of reading from the input.txt file. Moreover output it showing up inside the terminal.

Here's the commands I used inside Programs folder:  
1.  g++ test.cpp -o test.out
2. ./test.out

I tried the above commands after disabling Windows defender (I don't have any additional antivirus installed) and got the same result.

![1](https://user-images.githubusercontent.com/61842142/105383036-b33c6080-5c36-11eb-8324-076cfbd83754.PNG)

P.S.: Ctrl+Shift+B is producing the same error.

**Comment by jspw** [comment]
@sandip2224  i think it's the test.exe file which is making the error ! Delete this and try `ctrl+shift+b`

**Comment by sandip2224** [comment]
Tried reinstalling MinGW and re-checked environment variable path. 

So weird but now it WORKS just fine with `Ctrl+Shift+b` using test cases from `input.txt` and prints result to `output.txt`. Only had to add these lines inside my main() function.
```
freopen("input.txt","r",stdin);
freopen("output.txt","w",stdout);
```
**Could you please explain how/why this works?**


P.S.: I used the following manual build commands:
1. **g++ test.cpp -o test.out** 
2.  **./test.out**

**Comment by jspw** [comment]
MinGW was working fine in your machine that's why i asked to use manual commands.
Isn't it working without "freopen" in your main function ?
And i have also asked a question that "was my script creating the exe file ? " @sandip2224

**Comment by sandip2224** [comment]
No the `Ctrl + Shift + b` isnt creating the .exe file

**Comment by jspw** [comment]
If it's not creating the exe file then just delete the exe file and try the shortcut (Ctrl + Shift + b) ?

**Comment by sandip2224** [comment]
I just did. It's stuck at `./test.out`.

**Comment by jspw** [comment]
using `Ctrl + Shift + b` in vscode got stuck in ./test.out? I am not saying to use manual command from the terminal .

**Comment by sandip2224** [comment]
Okay give me a second

**Comment by jspw** [comment]
give me the whole screenshot kindly.

**Comment by sandip2224** [comment]
Before running `Ctrl+Shift+b`:
![1](https://user-images.githubusercontent.com/61842142/105463111-985d0100-5cb5-11eb-9f3f-1d190fb2a39c.PNG)
After running `Ctrl+Shift+b`:
![2](https://user-images.githubusercontent.com/61842142/105463135-a1e66900-5cb5-11eb-98d0-b98402f60897.PNG)

**Comment by jspw** [comment]
which task.json file you are using? 
The fisrt one when you got the launch faild error and now you are giving me  the pictures are not using same script i guess!
And 2nd question is : "where is the exe coming from ?
![p1](https://user-images.githubusercontent.com/40170955/105463530-639f7880-5cba-11eb-874d-8b997c40da16.png)

![image](https://user-images.githubusercontent.com/40170955/105463694-a4978d00-5cba-11eb-9f4c-9f23df22dda8.png)

**Comment by sandip2224** [comment]
O great finally it works. Seems like I had McAfee working all the while.

**Comment by jspw** [comment]
Yup that's why I told you to check your free antivirus :3  
btw I'm closing this issue .
