### ISSUE TITLE
Problem regarding Task.json file Windows

### ISSUE THREAD

**Issue by varungupta333** [jspw/VS-Code-Config#6]
I had recently updated my laptop and PowerShell would also have had been updated with that. Currently there were two errors 
1. "&&" was not being recognised but it was corrected using "-and", I don't know if it will work or not but yes.
2. I have attached the image of the associated error where it is showing "The '<' operator is reserved for future use."
![image](https://user-images.githubusercontent.com/50885553/134351094-72d3cacb-9c47-4326-9095-c2b39eb017a1.png)

**Comment by jspw** [comment]
Thanks @varungupta333  i will check it. windows sucks :3

**Comment by minorThreatOG** [comment]
one '}' is missingat the end of code...

**Comment by jspw** [comment]
can you tell me which file you are talking about ? @minorThreatOG

**Comment by minorThreatOG** [comment]
> can you tell me which file you are talking about ? @minorThreatOG

That .json file for c++(windows)...

**Comment by jspw** [comment]
is this still a issue ? @varungupta333  @minorThreatOG  
else i'm gonna close that.

**Comment by jspw** [comment]
hey @minorThreatOG  , i couldn't find any parenthesis (`}`) missing in the `.json` file . !
